### ISSUE TITLE
Look into migrating to content collections

### ISSUE THREAD

**Issue by usrme** [usrme/website#13]
When deploying the latest changes I saw the following in the build output:

```text
...
3:08:46 PM: ⚠️  Skipping draft src/pages/tils/a-way-to-diff-files-archives-and-directories-using-diffoscope.md
3:08:46 PM: 12:08:46 PM [astro] The drafts feature is deprecated. You should migrate to content collections instead.
See https://docs.astro.build/en/guides/content-collections/#filtering-collection-queries for more information.
...
```

So perhaps there's a new a better way to do things using [this](https://docs.astro.build/en/guides/content-collections/#filtering-collection-queries) as a basis.

**Comment by andreasvirkus** [comment]
So it's mainly working on the `issue-13` branch. The only weird thing with TILs is that Astro seems to render the `tils/[...slug].astro` file twice (as you can see it logs the `post prop` line 2x). The first render is with our expected file (props contain the right data); the 2nd render is with Astro's default frontmatter/content props (so not via the collection) 🤔 And that's where it errors out atm.

Also added Prettier and ran some auto formatting

**Comment by usrme** [comment]
@andreasvirkus, how would the change to `/blog/<some slug>` affect existing posts that are being linked to elsewhere, would they redirect automatically? Otherwise I don't mind any structure change if that is what makes things working sanely and predictably.

Regarding the error: why would there even be two renders?

**Comment by andreasvirkus** [comment]
The redirects can be handled by Netlify, you'd need a `netlify.toml` file in your repo root:
```
[[redirects]]
  from = "/post*"
  to = "/blog:splat"
  status = 301
```

Re error: unsure, very weird 🤔 Needs more wasted hours to figure out its essence 😄

**Comment by usrme** [comment]
After just upgrading to Astro 4 with commit https://github.com/usrme/website/commit/17d309435debc0a2c2bc1bff622a14d99c46071f the initial warning above disappeared from the build output and all of the previous/next logic still remained intact, so...

We'll never get the time back we spent messing with this, but we'll at least take solace in the fact that we won't have to spend any _more_ time on this! :tada:
